### ISSUE TITLE
Unclear how this works with of-watchdog / stateless microservices

### ISSUE THREAD

**Issue by alexellis** [grycap/oscar-worker#16]
Hi, I was reading some of the code and noticed a line that echos an input the call a process called "fprocess".

I'm unclear on how this would work with the of-watchdog templates and stateless micro services?

https://github.com/grycap/oscar-worker/blob/master/oscarworker/kubernetesclient.py#L130

Is this a use-case you are considering supporting?

More context:

- https://docs.openfaas.com/cli/templates/#templates
- https://docs.openfaas.com/reference/workloads/

My concerns are that the implementation doesn't respect the workload definition, and may rely on too much internal knowledge. Perhaps an alternative may involve a similar approach where the existing container is run, but with a sidecar that invokes it once?

Alex

**Comment by alexellis** [comment]
This also looks relevant: https://github.com/kubernetes/kubernetes/issues/25908#issue-155832874 cc @lucasroesler

**Comment by srisco** [comment]
Currently we have only worked with the classic watchdog. We'll take a look at the of-watchdog to see if we can make it compatible, but I don't think it's a necessary requirement to use functions that create an http server for batch jobs.

On the other hand, the idea of using sidecars was to have some method to make the callback with the result of the execution. This is not implemented since it is not necessary for our use of OSCAR Worker. However, I did tests using an init-container to process the function and a container to make a POST request with the result to the webhook specified in 'X-Callback-Url'. All this in the same k8s job.

**Comment by alexellis** [comment]
I was also doing some testing on this, this morning.

How did you specify the init container? via annotation?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: echo
spec:
  template:
    spec:
      containers:
      - name: figlet
        image: functions/figlet:latest
        command: ["fwatchdog"]
      - name: echo
        image: busybox
        command: ["/bin/wget", "127.0.0.1:8080", "--post-data=hi", "-O-"]
      restartPolicy: OnFailure
  backoffLimit: 4
```

**Comment by alexellis** [comment]
> I don't think it's a necessary requirement to use functions that create an http server for batch jobs.

For compatibility with OpenFaaS, it is because the workload definition states that: https://docs.openfaas.com/reference/workloads/

Therefore this interface would be compatible with 100% of OpenFaaS workloads (zero-touch) if you were to consider the side-car / init-container approach.

**Comment by srisco** [comment]
> I was also doing some testing on this, this morning.
> 
> How did you specify the init container? via annotation?
> 
I tested this:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-callback
spec:
  template:
    spec:
      initContainers:
      - name: figlet
        image: functions/figlet:latest
        args:
        - /bin/sh
        - -c
        - "echo $EVENT | $fprocess 2>&1 | tee /var/log/output.log"
        env:
        - name: EVENT
          value: Hello!!
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      containers:
      - name: callback
        image: grycap/wget
        command: [sh]
        args:
        - -c
        - "wget --post-file=/var/log/output.log --no-check-certificate $CALLBACK_URL"
        env:
        - name: CALLBACK_URL
          value: https://my-webhook
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        emptyDir: {}
      restartPolicy: OnFailure

```
The idea is to execute the "fprocess" directly. Watchdog is not necessary in a job because every single job process one invocation (event). As the OpenFaaS functions (at least with classic watchdog) receive the event via standard input, this approach would be compatible with them, as well as with any program that receives parameters by stdin.
